name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.4'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby w/o bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: none
        bundler-cache: false
      run: |
        bundle config set --local path 'vendor/bundle'

    - name: Install versionary manually in vendor/bundle/ruby/3.0.0
      run: |
        gem install --no-user-install --install-dir vendor/bundle/ruby/3.0.0 versionomy

    - name: Set up Ruby normally now
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build the documentation
      run: bundle exec rake doc:yard

# Local Variables:
# mode: yaml
# eval: (if (intern-soft "fci-mode") (fci-mode 1))
# End:
